package canreg.client.gui.dataentry2;

import canreg.common.database.DatabaseRecord;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.application.Action;

/**
 *
 * @author c_chen
 */
public class RecordEditorSourceSelectorInternalFrame extends javax.swing.JDialog {
    
    String selectedValue;
    String validatedValue;
    HashMap<Integer, String> mapTumourNumberDisplayed_tumourId;

    /**
     * Creates new customizer SourceSelector
     */
    public RecordEditorSourceSelectorInternalFrame(LinkedList<RecordEditorTumour> tumours) {
        mapTumourNumberDisplayed_tumourId = new HashMap();
        this.validatedValue = null;
        this.selectedValue = "none";
        ListSelectionModel listSelectionModel;
        initComponents();
        label1.setText("Select the tumour where to move the source");
        jButton1.setText("Ok");
        
        ArrayList<String> tumoursList = new ArrayList<>();
        tumours.forEach(tumour -> {
            DatabaseRecord a = tumour.getDatabaseRecord();
            String tumorRecordNumber = a.getVariableAsString("tumourid");
            String tumorTableId = a.getVariableAsString("patientrecordidtumourtable");
            if (tumorRecordNumber.length() != 0) {
                int tumorNumber = Integer.parseInt(tumorRecordNumber.substring(tumorTableId.length()));
                tumoursList.add("Tumour "+tumorNumber);
                mapTumourNumberDisplayed_tumourId.put(tumorNumber, tumorRecordNumber);
            }
        });
        
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = tumoursList.toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSelectionModel = jList1.getSelectionModel();
        listSelectionModel.addListSelectionListener(new SharedListSelectionHandler());
        setVisible(true);
    }
    
    class SharedListSelectionHandler implements ListSelectionListener {
        public void valueChanged(ListSelectionEvent e) { 
            ListSelectionModel lsm = (ListSelectionModel)e.getSource();

            if (lsm.isSelectionEmpty()) {
                selectedValue = "none";
            } else {
                // Find out which indexes are selected.
                int minIndex = lsm.getMinSelectionIndex();
                int maxIndex = lsm.getMaxSelectionIndex();
                for (int i = minIndex; i <= maxIndex; i++) {
                    if (lsm.isSelectedIndex(i)) {
                        selectedValue = "" + jList1.getSelectedValue().substring("Tumour ".length());
                        System.out.print("SELECTED: ");
                        System.out.println(selectedValue);
                    }
                }
            }
        }
    }
    
    public String getValidatedTumourId() {
        return this.validatedValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setTitle("Select target tumour");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("label2");
        getContentPane().add(label1, java.awt.BorderLayout.PAGE_START);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(RecordEditorSourceSelectorInternalFrame.class, this);
        jButton1.setAction(actionMap.get("validateTumour")); // NOI18N
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void validateTumour() {
        System.out.println("OK BUTTON PRESSED");
        this.validatedValue = mapTumourNumberDisplayed_tumourId.get(Integer.valueOf(this.selectedValue));
        System.out.print("FROM SELECTOR: ");
        System.out.println(this.validatedValue);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
